INSERT INTO BOOK(name, author, publisher, price) VALUES('追风筝的人', '[美] 卡勒德·胡赛尼 著 李继宏 译', '上海人民出版社', 36.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('苏菲的世界（新版）：教育部推荐新课标课外阅读', '乔斯坦·贾德 著', '作家出版社', 38.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 会计 上下册', '张志凤 著', '北京科学技术出版社', 99.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 经济法 上下册', '郭守杰 著', '北京科学技术出版社', 89.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('余华作品：活着', '余华 著', '作家出版社', 28.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 财务成本管理 上下册', '闫华红 著', '北京科学技术出版社', 94.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES(' 浮生六记（汪涵推荐，全译本，畅销150万册）', '沈复 著 张佳玮 译', '天津人民出版社', 32.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('悟空传（今何在现象级长销作品热血回归，2016修订版！彭于晏倪妮主演同名电影已经上映）', '今何在 著', '北京联合出版公司', 32.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('东野圭吾四大推理套装（共4册）', '东野圭吾 著', '南海出版公司', 159.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('刘同：我在未来等你', '刘同 著', '北京联合出版公司', 42.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('原则', '瑞·达利欧 著 刘波 綦相 译', '中信出版集团，中信出版社', 98.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('自卑与超越（完整全译本）', '[奥地利] 阿尔弗雷德.阿德勒 著 曹晚红 译', '中国友谊出版公司', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('生活需要仪式感', '李思圆 著', '山东文艺出版社', 36.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 税法 上下册', '刘颖 著', '北京科学技术出版社', 99.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材 2018年注册会计师全国统一考试辅导教材 CPA 会计', '中国注册会计师协会 编', '中国财政经济出版社', 88.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('流量池', '杨飞 著', '中信出版社，中信出版集团', 68.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('父与子全集（套装共10册）', '[德] 埃·奥·卜劳恩 著 高杨 译', '中国和平出版社', 120.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('半小时漫画世界史', '陈磊 著', '江苏凤凰文艺出版社', 39.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES('天才在左疯子在右完整版　[荐书联盟推荐]', '高铭 著', '北京联合出版公司', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('高难度谈话（2018新版）', '[美] 道格拉斯斯通 [美] 布鲁斯佩顿 [美] 希拉汉 著 王甜甜 译', '光明日报出版社', 45.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中级会计职称2018教材东奥会计 轻松过关1 2018年会计专业技术资格考试应试指导及全真模拟测试：中级会计实务（上下册）', '张志凤 著', '北京科学技术出版社', 70.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('摆渡人　【荐书联盟推荐】', '[英] 克莱儿·麦克福尔 著 付强 译', '百花洲文艺出版社', 36.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('斗罗大陆第三部龙王传说26', '唐家三少 著', '湖南少年儿童出版社', 29.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('人间词话（汪涵推荐的珍藏版，精装插图全译本）【作家榜经典出品】', '王国维 著 陈家泠 于非闇 绘 周公度 译', '浙江文艺出版社', 56.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('北斗童书·孩子，你会更优秀（套装全4册）', '[德] 安格莉卡·巴特拉姆 [德] 扬-乌韦·罗格 著 [德] 安内特·沃博达 绘 朱显亮 王晚蕾 译', '天津人民出版社', 88.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中级会计职称2018教材 2018年全国会计专业技术初级资格考试辅导教材：中级会计资格 中级会计实务', '财政部会计资格评价中心 著', '经济科学出版社', 56.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中级会计职称2018教材东奥会计 轻松过关1 2018年会计专业技术资格考试应试指导及全真模拟测试：中级经济法（上下册）', '黄洁洵 著', '北京科学技术出版社', 72.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('勇气', '[美] 伯纳德·韦伯 著 阿甲 译', '北京联合出版公司', 35.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('这样爱你刚刚好我的一年级孩子/新父母教材', '朱永新 孙云晓 刘秀英 著', '湖南教育出版社', 48.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('自控力 斯坦福大学广受欢迎心理学课程（新版）', '[美] 凯利·麦格尼格尔 著', '文化发展出版社（原印刷工业出版社）', 45.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('北斗童书·英国专注力培养丛书系列-5分钟玩出专注力（风靡欧洲脑力训练 套装共4册）', '[英] 丽莎·里根 著', '中国人口出版社', 59.20);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 公司战略与风险管理 上下册', '田明 著', '北京科学技术出版社', 85.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('正面管教（修订版）', '简·尼尔森 著 玉冰 译', '北京联合出版公司', 38.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('百万英镑/经典译林', '[美] 马克·吐温 著 宋兆霖 编 张友松 等 译', '译林出版社', 28.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('皮囊', '蔡崇达 著', '天津人民出版社', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中级会计职称2018教材 2018年全国会计专业技术初级资格考试辅导教材：中级会计资格 经济法', '财政部会计资格评价中心 著', '经济科学出版社', 56.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('硬派健身：你的第一本健身书', '斌卡 著', '湖南文艺出版社', 48.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('余光中作品 ：长长的路 我们慢慢走', '余光中 著', '光明日报出版社', 49.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES('月亮与六便士（2017新版！未删节插图珍藏本）（作家榜经典）', '[英] 毛姆 著 [法] 高更 绘 波比文化小说奖得主 徐淳刚 译', '浙江文艺出版社', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('星火英语 英语四级真题试卷 2018年6月全真试题+标准模拟 词汇写作翻译听力阅读口语', '汪开虎 著', '上海交通大学出版社', 56.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('数学之美（第二版） ', '吴军 著', '人民邮电出版社', 49.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材东奥轻松过关1应试指导及全真模拟测试 审计 上下册', '刘圣妮 著', '北京科学技术出版社', 99.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材 2018年注册会计师全国统一考试辅导教材 CPA 税法', '中国注册会计师协会 著', '中国财政经济出版社', 72.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('解忧杂货店', '[日] 东野圭吾 著 李盈春 译', '南海出版公司', 39.50);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中级会计职称2018教材 2018年全国会计专业技术初级资格考试辅导教材：中级会计资格 财务管理', '财政部会计资格评价中心 著', '经济科学出版社', 47.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('中国科幻基石丛书·三体（套装1-3册）', '刘慈欣 著', '重庆出版社', 93.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('习近平谈治国理政 第二卷（中文平装）', '习近平 著', '外文出版社', 80.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('半小时漫画中国史', '二混子 著', '江苏凤凰文艺出版社', 39.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES('在教室说错了没关系', '[日] 莳田晋至 著 [日] 长谷川知子 绘 纪鑫 译', '青岛出版社', 36.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('怪物大师19：绝望的圣城囚笼', '雷欧幻像 著', '接力出版社', 15.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('影响力（经典版）（新版）', '[美] 罗伯特·B·西奥迪尼 著 闾佳 译', '北京联合出版公司', 54.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES(' 中级会计职称2018教材东奥会计 轻松过关1 2018年会计专业技术资格考试应试指导及全真模拟测试：中级财务管理（上下册）', '闫华红 著', '北京科学技术出版社', 69.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('所谓情商高，就是会说话', '佐佐木圭一 著 程亮 译', '北京联合出版公司', 32.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('浮生六记（新版！贾平凹汪涵推荐，无删节插图珍藏本）【作家榜经典出品】', '[清] 沈复 著 张朝晖 尧立 陆伟黎 绘 周公度 译', '浙江文艺出版社', 45.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('习近平的七年知青岁月 ', '中央党校采访实录编辑室 著', '中共中央党校出版社', 76.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('见识', '吴军 著', '中信出版集团，中信出版社', 49.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('可爱的数学（套装全8册）', '谢茹 著', '中国人口出版社', 108.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('卓有成效的管理者（珍藏版） ', '[美] 彼得·德鲁克 著', '机械工业出版社', 30.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材 2018年注册会计师全国统一考试辅导教材 CPA 经济法', '中国注册会计师协会 著', '中国财政经济出版社', 68.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('俗世奇人1+2（套装共2册）', '冯骥才 著 钱英 编', '作家出版社', 40.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('南渡北归系列（全新经典版，套装全3册）', '岳南 著', '湖南文艺出版社', 195.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('绩效核能（精装行动版）', '李太林 著', '北京联合出版公司', 46.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('乌合之众（原版插图，无删减版）', '[法] 古斯塔夫·勒庞 著', '中国妇女出版社', 36.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('山本（贾平凹2018年新作）', '贾平凹 著', '作家出版社', 59.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('蔡康永的说话之道（套装共2册）', '蔡康永 著', '湖南文艺出版社', 65.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('林徽因：不慌不忙的坚强', '赵一 著', '哈尔滨出版社', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('星火英语 英语六级真题试卷 2018年6月全真试题+标准模拟 词汇写作翻译听力阅读口语', '汪开虎 著', '上海交通大学出版社', 56.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('荒野求生少年生存小说系列：中国雨林的惊天一跃', '[英] 贝尔·格里尔斯 著 王旸 唐思雨 译', '接力出版社', 22.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('平凡的世界：全三册', '路遥 著', '北京十月文艺出版社', 108.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('非暴力沟通', '马歇尔·卢森堡 著', '华夏出版社', 33.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('日本心灵成长绘本·小小的我（让小小的我勇敢面对大大的世界）', '日野原重明 笠井真理 冈田千晶 著', '中国人口出版社', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('高效能人士的七个习惯（25周年纪念版）', '[美] 史蒂芬·柯维 著 高新勇 王亦兵 葛雪蕾 译', '中国青年出版社', 68.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('新华字典（双色本 第11版） ', '商务印务馆 编', '商务印书馆', 24.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES('童立方·凯迪克银奖绘本：瞌睡虫', '[美] 戴安娜·斯奈德 著 [美] 艾伦·塞伊 绘', '辽宁少年儿童出版社', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('偷影子的人（随书附精美卡片）', '[法] 马克·李维 著 段韵灵 译', '湖南文艺出版社', 29.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('时间简史（插图版）【荐书联盟推荐】', '[英] 史蒂芬·霍金 著 许明贤 吴忠超 译', '湖南科学技术出版社', 45.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('为何家会伤人', '武志红 著 冯倩 编', '北京联合出版公司', 39.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('幼儿睡前故事绘本(全套60册) 0-3-6岁童话书儿童启蒙认知早教', '罗自国 等 绘', '文化发展出版社', 120.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('荒野求生少年生存小说系列（套装共12册）', '[英] 贝尔·格里尔斯 著', '接力出版社', 264.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('企鹅萌萌 婴幼儿童互动手工涂色绘本 AR涂色乐园（套装共6册）', '上海仙剑文化传媒股份有限公司 著', '山东美术出版社', 112.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('现代汉语词典（第7版）', '中国社会科学院语言研究所词典编辑室 编', '商务印书馆', 109.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('AR立体贴纸书（套装共6册）儿童粘贴纸书 3-6岁', '上海仙剑文化传媒股份有限公司 著', '山东美术出版社', 64.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('习近平谈治国理政第一卷（2018再版）', '习近平 著', '外文出版社', 80.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('边城（纪念典藏版）', '沈从文 著', '武汉出版社', 35.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('Python编程 从入门到实践 ', '[美] 埃里克·马瑟斯 著 袁国忠 译', '人民邮电出版社', 89.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('不会讲故事，怎么带团队（荣获AXIOM年度商业图书金奖！）：新版', '[澳] 肖恩.卡拉汉 著', '中国友谊出版公司', 49.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('鸟哥的Linux私房菜 （基础学习篇 第三版） ', '鸟哥 著 王世江 编', '人民邮电出版社', 88.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('高兴死了！！！', '[美] 珍妮·罗森 著 吴洁静 译', '江苏文艺出版社', 59.90);
INSERT INTO BOOK(name, author, publisher, price) VALUES('长安十二时辰（上下共两册）', '马伯庸 著', '湖南文艺出版社', 79.60);
INSERT INTO BOOK(name, author, publisher, price) VALUES('自在独行：贾平凹的独行世界（陈坤推荐）', '贾平凹 著', '长江文艺出版社', 39.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('吴晓波企业史 激荡十年，水大鱼大', '吴晓波 著', '中信出版集团，中信出版社', 58.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('断舍离', '[日] 山下英子 著 吴倩 译', '广西科学技术出版社', 32.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('知行合一王阳明套装大合集（1+2+3+传习录）(共4册)', '度阴山 著', '北京时代华文书局，北京联合出版公司', 144.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('听你的（张皓宸2018全新力作，赠送精美杯垫）', '张皓宸 著', '天津人民出版社', 49.80);
INSERT INTO BOOK(name, author, publisher, price) VALUES('小家，越住越大2（京东尊享拉页版）', '逯薇 著', '中信出版集团', 68.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('英语单词大书（附原版音频）', '[英] 梅丽·麦金农 著 凯特·欣德利 绘', '北京联合出版公司', 78.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('不一样的卡梅拉手绘版·第一季（套装12册）', '[法] 克利斯提昂·约里波瓦 著 [法] 克利斯提昂·艾利施 绘 郑迪蔚 译', '二十一世纪出版社', 120.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('注册会计师2018教材 2018年注册会计师全国统一考试辅导教材 CPA 财务成本管理', '中国注册会计师协会 著', '中国财政经济出版社', 60.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('请不要随便摸我  (全彩)', '[美] Cornelia Spelman 著 于水 译', '电子工业出版社', 35.00);
INSERT INTO BOOK(name, author, publisher, price) VALUES('摆渡人2重返荒原', '[英] 克莱儿·麦克福尔 著 付强 译', '百花洲文艺出版社', 42.80);